### ISSUE TITLE
Not an issue!

### ISSUE THREAD

**Issue by GioF71** [tehkillerbee/mopidy-tidal#156]
Thank you! you're the man! :-)
Who needs shady tidal-connect binaries anymore?

**Comment by GioF71** [comment]
I've prepared a docker image and a sample configuration [here](https://github.com/GioF71/audio-tools/tree/main/players/mopidy-tidal).
Maybe it could be useful for other users.
Cheers

**Comment by tehkillerbee** [comment]
@GioF71 Very cool. I'd like to add it as a recommendation to the mopidy-tidal readme, if you don't mind.

This will come in handy, as I have an ancient python version 3.8 on my laptop at work, making it difficult to install mopidy without workarounds.

**Comment by GioF71** [comment]
Of course! It's a pleasure

**Comment by GioF71** [comment]
I just noticed that I this morning I forgot to trigger the pipeline that pushes the images to docker hub. It's running now, so these will include the latest version 0.3.6

**Comment by tehkillerbee** [comment]
Great, it worked with some smaller hiccups.

* docker-compose is apparently deprecated so I needed to use docker compose instead.
* Needed to use `AUDIO_OUTPUT=autoaudiosink`  (or `alsasink device=hw:3,0` for SMSL M300SE) instead of =`default`, otherwise gstreamer would complain: `Failed to create audio output "default": gst_parse_error: no element "default`
* Needed to setup pulseaudio slightly differently, otherwise I got errors when starting playback. 
* `alsasink device=hw:3,0`
```
Could not open audio device for playback. Device is being used by another application.
```
For the above error, I just needed to make sure the host system was not using the DAC.

* `autoaudiosink`
```
Failed to create secure directory (//.config/pulse): No such file or directory
Failed to create secure directory (//.config/pulse): No such file or directory
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
```
To fix the above error, I added the following, as per https://comp0016-team-24.github.io/dev/problem-solving/2020/10/30/passing-audio-into-docker.html and used `autoaudiosink`. For `alsasink device=hw:3,0`, this was not necessary. I also tried accessing the DAC through autoaudiosink and it worked but only at the default bitrate.
* Enabled all volumes (cache, data, dconf) to allow loading tidal session at startup and reloading cached images etc.

The resulting docker-compose.yml:
```
services:
  mopidy:
    image: ${MOPIDY_IMAGE_REPO:-docker.io}/giof71/mopidy:${MOPIDY_IMAGE_TAG:-latest}
    container_name: mopidy-tidal
    user: "${PUID}:${AUDIO_GID}"
    devices:
      - /dev/snd:/dev/snd
    environment:
      - AUDIO_OUTPUT=${AUDIO_OUTPUT:-default}
      - TIDAL_ENABLED=${TIDAL_ENABLED:-yes}
      - TIDAL_QUALITY=${TIDAL_QUALITY:-LOSSLESS}
      - TIDAL_AUTH_METHOD=${TIDAL_AUTH_METHOD:-OAUTH}
      - TIDAL_LOGIN_SERVER_PORT=${TIDAL_LOGIN_SERVER_PORT:-8989}
      - PULSE_SERVER=unix:/run/user/${PUID}/pulse/native
    ports:
      - ${MOPIDY_PORT:-6680}:6680
      - ${TIDAL_LOGIN_SERVER_PORT:-8989}:${TIDAL_LOGIN_SERVER_PORT:-8989}
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./data:/data
      - ./dconf:/.cache/dconf
      - /run/user/${PUID}/pulse/native:/run/user/${PUID}/pulse/native
      - ./config/pulse/cookie:/root/.config/pulse/cookie
    restart: always
```

**Comment by GioF71** [comment]
About this:

> Could not open audio device for playback. Device is being used by another application.

it is expected when trying to access an alsa device when pulseaudio is running. A simple fix is telling pulseaudio to ignore the device. Look at the Xmos device (last of the list) which is "off" using PulseAudio Volume Control

![image](https://github.com/tehkillerbee/mopidy-tidal/assets/5603160/ed99187f-105e-48f8-951d-de622b5d446a)

**Comment by tehkillerbee** [comment]
A quick update, I made some changes to the docker-container to fix an issue that occurred after reboot. With the previous config, my pulseaudio server would not be able to start, resulting in no audio on the host system.
```
---
version: "3.3"

services:
  mopidy:
    image: ${MOPIDY_IMAGE_REPO:-docker.io}/giof71/mopidy:${MOPIDY_IMAGE_TAG:-latest}
    container_name: mopidy-tidal
    user: "${PUID}:${AUDIO_GID}"
    devices:
      - /dev/snd:/dev/snd
    environment:
      - AUDIO_OUTPUT=${AUDIO_OUTPUT:-default}
      - TIDAL_ENABLED=${TIDAL_ENABLED:-yes}
      - TIDAL_QUALITY=${TIDAL_QUALITY:-LOSSLESS}
      - TIDAL_AUTH_METHOD=${TIDAL_AUTH_METHOD:-OAUTH}
      - TIDAL_LOGIN_SERVER_PORT=${TIDAL_LOGIN_SERVER_PORT:-8989}
      # set path to pulseaudio socket as specified in -v
      - PULSE_SERVER=unix:/run/user/${PUID}/pulse/native
      # set path to PULSE_COOKIE as specified in -v
      - PULSE_COOKIE=/run/pulse/cookie
    ports:
      - ${MOPIDY_PORT:-6680}:6680
      - ${TIDAL_LOGIN_SERVER_PORT:-8989}:${TIDAL_LOGIN_SERVER_PORT:-8989}
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./data:/data
      - ./dconf:/.cache/dconf
      - /run/user/${PUID}/pulse/native:/run/user/${PUID}/pulse/native
      - /home/${USER}/.config/pulse/cookie:/run/pulse/cookie
    restart: always
```
